In [1]:
pip install causalml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 406 kB 5.4 MB/s 
     |████████████████████████████████| 564 kB 48.6 MB/s 
     |████████████████████████████████| 1.8 MB 44.2 MB/s 
     |████████████████████████████████| 718 kB 48.5 MB/s 
  Created wheel for causalml: filename=causalml-0.12.3-cp37-cp37m-linux_x86_64.whl size=1054262 sha256=57f40038b34384b51097e085cc60a8315e6b0f1035ffc04d2e565cd518f9eebc
  Stored in directory: /root/.cache/pip/wheels/d7/5e/47/4e965cf8e87c6c10cd7361d910acccd08a1de459f25d55fd23
Successfully built causalml


In [2]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from causalml.dataset import synthetic_data

y, X, treatment_flags, ite_list, exp_outcome_list, e = synthetic_data(mode=1, n=10_000, p=5, sigma=1.0)

print(f"Sample outcome: {y[:5]}")
print(f"Sample independent variables: {X[:5]}")

print(f"Treatment Data Count = {np.count_nonzero(treatment_flags)}")
print(f"Control Data Count = {len(y) - np.count_nonzero(treatment_flags)}")

print(f"Sample ITE: {ite_list[:5]}")

Sample outcome: [4.16603802 2.66343101 1.73090528 1.51348602 2.23708666]
Sample independent variables: [[0.80332286 0.68494985 0.46040221 0.5201406  0.63149635]
 [0.86448588 0.31806375 0.8828936  0.53621287 0.84205469]
 [0.47853946 0.34292117 0.4600919  0.43675847 0.83207349]
 [0.05508973 0.56560549 0.21877477 0.19707483 0.41018617]
 [0.43129212 0.37779253 0.5288168  0.98852722 0.73954197]]
Treatment Data Count = 5138
Control Data Count = 4862
Sample ITE: [0.74413636 0.59127482 0.41073032 0.31034761 0.40454233]


In [3]:
from causalml.inference.meta import LRSRegressor

lr = LRSRegressor()
print(lr)

LRSRegressor(model=<causalml.inference.meta.slearner.StatsmodelsOLS object at 0x7fcd5f9f9990>)


In [4]:
te, lb, ub = lr.estimate_ate(X, treatment_flags, y)
print(f"Confidence Level Alpha = {lr.ate_alpha}")
print(f"ATE = {np.round(te[0], 2)}, Range : {np.round(lb[0], 2)}:{np.round(ub[0], 2)}")

Confidence Level Alpha = 0.05
ATE = 0.66, Range : 0.61:0.71
